# Generated by Django 6.0.2 on 2026-02-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_deactivate_tours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
